ktor:
  application:
    modules:
      - io.github.binaryyouchien.ensokukaido.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
db:
  mongo:
    user: root
    password: youtien
    database_name: mongo