services:
  #########################################################
  front-init-rsync:
    image: secoresearch/rsync
    user: root:root
    command: [
      rsync, --delete, -av, /src/, /app,
      --exclude, node_modules,
      --exclude, /.vite,
    ]
    working_dir: /src
    volumes:
      - type: bind
        source: .
        target: /src
      - type: volume
        source: front-app-data
        target: /app
  #########################################################
  front-init:
    image: node
    command: [ npm, ci ]
    depends_on:
      front-init-rsync:
        condition: service_completed_successfully
    working_dir: /app
    volumes:
      - type: volume
        source: front-app-data
        target: /app
      - type: volume
        source: front-root
        target: /root
  #########################################################
  front-test:
    image: node
    command: [ npm, run, build ]
    depends_on:
      front-init-rsync:
        condition: service_completed_successfully
      front-init:
        condition: service_completed_successfully
    working_dir: /app
    volumes:
      - type: volume
        source: front-app-data
        target: /app
      - type: volume
        source: front-root
        target: /root
  #########################################################
volumes:
  front-app-data:
  front-root:
